3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")
]

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('',views.index_view,name="indexdata"),
    path('home/', views.home, name="home"),
    path('details/<int:id>/', views.detail, name="detail"),
    path('addmovies/', views.add_movies, name="add_movies"),
    path('editmovies/<int:id>/', views.edit_movies, name="edit_movies"),
    path('deletemovies/<int:id>/', views.delete_movies, name="delete_movie"),
    path('addreview/<int:id>/', views.add_review, name="add_review"),
    path('editreview/<int:movie_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('deletereview/<int:movie_id>/<int:review_id>/', views.delete_review, name="delete_review"),
    
]

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/moviereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Movie(models.Model):
    # fields for the movie table
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=800)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=5000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username
        

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/forms.py
from django import forms
from .models import *

# movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'description', 'release_date', 'image')
        
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment", "rating")

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Avg
# Create your views here.


def index_view(request):
    return render(request,'main/home.html')


def home(request):
    query = request.GET.get("title")
    allMovies = None
    if query:
        allMovies = Movie.objects.filter(name__icontains=query)
    else:
        allMovies = Movie.objects.all()  # select * from movie
    
    context = {
        "movies": allMovies,
    }
    return render(request, 'main/index.html', context)

# detail page
def detail(request, id):
    movie = Movie.objects.get(id=id) # select * from movie where id=id
    reviews = Review.objects.filter(movie=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average, 2)
    context = {
        "movie": movie,
        "reviews": reviews,
        "average": average
    }
    return render(request, 'main/details.html', context)


# add movies to the database
def add_movies(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = MovieForm(request.POST or None)

                # check if the form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:home")
            else:
                form = MovieForm()
            return render(request, 'main/addmovies.html', {"form": form, "controller": "Add Movies"})
        
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login")    


# edit the movie
def edit_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the movies linked with id
            movie = Movie.objects.get(id=id)

            # form check
            if request.method == "POST":
                form = MovieForm(request.POST or None, instance=movie)
                # check if form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:detail", id)
            else:
                form = MovieForm(instance=movie)
            return render(request, 'main/addmovies.html', {"form": form, "controller": "Edit Movies"})
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login") 


# delete movies
def delete_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the moveis
            movie = Movie.objects.get(id=id)

            # delte the movie
            movie.delete()
            return redirect("main:home")
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login") 

def add_review(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect("main:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form": form})
    else:
        return redirect("accounts:login")


# edit the review
def edit_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                         error = "Out or range. Please select rating from 0 to 10."
                         return render(request, 'main/editreview.html', {"error": error, "form": form})
                    else:
                        data.save()
                        return redirect("main:detail", movie_id)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html', {"form": form})
        else:
            return redirect("main:detail", movie_id)
    else:
        return redirect("accounts:login")


# delete reivew
def delete_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission to delete
            review.delete()

        return redirect("main:detail", movie_id)
            
    else:
        return redirect("accounts:login")

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/templates/main/addmovies.html
{% extends 'main/base.html' %} {% load crispy_forms_tags %} {% block content %} {% load static %}


<div class="container">
    <img class="img-responsive" src="{% static 'images/zoom.gif' %}" alt="" width="1110px" height="200px">
</div>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %} {{ form | crispy }}
                <input type="submit" value="{{ controller }}" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>


{% endblock %}

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/templates/main/base.html
<!doctype html> {% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <link rel="icon" href="{% static 'images/logo.png'  %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> {% load static %}
    <!-- font awsome -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

    <title>www.Moviereview.com</title>

</head>

<body>
    {% include "main/nav.html" %} {% block content %} {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/templates/main/details.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h3 class="text-center">
                    {{ movie.name }}
                </h3>
                <p>{{ movie.description }}</p>
                <h5>Director: {{ movie.director }}</h5>
                <h5>Cast: {{ movie.cast }}</h5>
                <h5>Rating: {{ average }}/10</h5>

                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                        <a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning">Edit Movie</a>
                        <a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger"  onclick="return confirm('Are you sure you want to delete this?');">Delete Movie</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Review</h3>
            <form action="{% url 'main:add_review' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                <label for="rating">Rating</label>
                <input type="range" id="rangeInput" 
                    name="rating" min="0" max="10" value="0" step="0.5"
                    oninput="amount.value=rangeInput.value">                                                       
         
         <output name="amount" id="amount" for="rangeInput">0</output>
                
                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
                <div class="card" style="background-color: #f5eeee;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <h5 class="text-left">{{ review.user.username }}</h5>
                                <h5>{{ review.rating }}</h5>
                                {% if request.user == review.user %}
                                <a href="{% url 'main:edit_review' movie.id review.id %}">Edit</a>
                                <a href="{% url 'main:delete_review' movie.id review.id %}" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                                {% endif %}

                            </div>
                            <div class="col-md-9">
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/templates/main/editreview.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}


{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/templates/main/home.html
{% extends 'main/base.html' %} {% load static %} {% block content %}


<style>
    .hovereffect {
        width: 100%;
        height: 100%;
        float: left;
        overflow: hidden;
        position: relative;
        text-align: center;
        cursor: default;
    }
    
    .hovereffect .overlay {
        width: 100%;
        height: 100%;
        position: absolute;
        overflow: hidden;
        top: 0;
        left: 0;
        background-color: rgba(75, 75, 75, 0.7);
        -webkit-transition: all 0.4s cubic-bezier(0.88, -0.99, 0, 1.81);
        transition: all 0.4s cubic-bezier(0.88, -0.99, 0, 1.81);
    }
    
    .hovereffect:hover .overlay {
        background-color: rgba(48, 152, 157, 0.4);
    }
    
    .hovereffect img {
        display: block;
        position: relative;
    }
    
    .hovereffect h2 {
        text-transform: uppercase;
        color: #fff;
        text-align: center;
        position: relative;
        font-size: 17px;
        padding: 10px;
        background: rgba(0, 0, 0, 0.6);
        -webkit-transform: translateY(45px);
        -ms-transform: translateY(45px);
        transform: translateY(45px);
        -webkit-transition: all 0.4s cubic-bezier(0.88, -0.99, 0, 1.81);
        transition: all 0.4s cubic-bezier(0.88, -0.99, 0, 1.81);
    }
    
    .hovereffect:hover h2 {
        -webkit-transform: translateY(5px);
        -ms-transform: translateY(5px);
        transform: translateY(5px);
    }
    
    .hovereffect a.info {
        display: inline-block;
        text-decoration: none;
        padding: 7px 14px;
        text-transform: uppercase;
        color: #fff;
        border: 1px solid #fff;
        background-color: transparent;
        opacity: 0;
        filter: alpha(opacity=0);
        -webkit-transform: scale(0);
        -ms-transform: scale(0);
        transform: scale(0);
        -webkit-transition: all 0.4s cubic-bezier(0.88, -0.99, 0, 1.81);
        transition: all 0.4s cubic-bezier(0.88, -0.99, 0, 1.81);
        font-weight: normal;
        margin: -52px 0 0 0;
        padding: 62px 100px;
    }
    
    .hovereffect:hover a.info {
        opacity: 1;
        filter: alpha(opacity=100);
        -webkit-transform: scale(1);
        -ms-transform: scale(1);
        transform: scale(1);
    }
    
    .hovereffect a.info:hover {
        box-shadow: 0 0 5px #fff;
    }
</style>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>




<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'images/slide1.png' %}" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/slide2.png' %}" alt="First slide">
        </div>



    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container mt-lg-5">
    <iframe width="1060" height="415" src="https://www.youtube.com/embed/V7LwfY5U5WI" title="YouTube video player" frameborder="5" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<div class="jumbotron">
    <div class="card text-center">
        <div class="card-header">
            ONLINE MOVIES
        </div>
        <div class="card-body">
            <h5 class="card-title">The Today Show is a morning staple for many people who've come to love the informative
            </h5>
            <p class="card-text">If you want to catch the Today Show on NBC live, you'll need to log into the website using login information for your TV provider. This might be Xfinity, DirecTV or something else. If you have a cable subscription, logging in is beneficial
                since you'll then have access not just to the Today Show, but to all of the available content on the site.
            </p>
            <a href="https://www.mxplayer.in/movies" target="_blank" class="btn btn-primary">Go somewhere</a>
        </div>
        <div class="card-footer text-muted">
            To Day Show
        </div>
    </div>


</div>



<div class="container">
    <div class="row">

        <div class="col-lg-3">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'images/7k.jpg' %}" alt="" style="width: 250px;height: 280px;border: 12px solid gainsboro;">
                <div class="overlay">
                    <h2>Hindhi</h2>
                    <a href="#" class="btn btn-success">Avalible</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'images/8k.jpg' %}" al style="width: 250px;height: 280px;border: 12px solid rgb(179, 28, 28);" t="">
                <div class="overlay">
                    <h2>English</h2>
                    <a href="#" class="btn btn-success">Avalible</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'images/5k.jpg' %}" alt="" style="width: 250px;height: 280px;border: 12px solid gainsboro;">
                <div class="overlay">
                    <h2>Tamil</h2>
                    <a href="#" class="btn btn-success">Avalible</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3">
            <div class="hovereffect">
                <img class="img-responsive" src="{% static 'images/6k.jpg' %}" alt="" style="width: 250px;height: 280px;border: 12px solid gainsboro;">
                <div class="overlay">
                    <h2>France</h2>
                    <a href="#" class="btn btn-success">Avalible</a>
                </div>
            </div>
        </div>
    </div>
</div>





<!-- <div class="container">
    <div class="row">
        <div class="col-md-4">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/s-bZD3O3P80" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div> -->

<br>
<br>
<br> {% endblock content %}

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}


<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                            <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                            <h3 class="text-center">{{ movie.name }}</h3>
                            
                            <i class="text-center">{{ movie.release_date }}</i>
                            <a href="{% url 'main:detail' movie.id %}">Read More</a>
                        </div>
                        
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

3-12/3-12-Movie -sanchitha/MOVIE_EXAMPLES/main/templates/main/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white h-75">
    <a class="navbar-brand " href="{% url 'main:home' %}">MOVIE DATABASE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">SEARCH</button>
    </form>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link mx-5" href="{% url 'main:indexdata' %}">HOME <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link mx-5" href="{% url 'main:home' %}">MOVIES <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link mx-5" href="{% url 'main:add_movies' %}">CREATE&nbsp;MOVIES</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item mx-5" href="#">MY PROFILE</a>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item mx-5" href="{% url 'accounts:logout' %}">LOGOUT</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link mx-5" href="{% url 'accounts:login' %}">LOGIN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link mx-5" href="{% url 'accounts:register' %}">REGISTER</a>
            </li>
            {% endif %}

        </ul>

    </div>
</nav>